name: Full-year calendar

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
